
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:
    
    docker:
      - image: cimg/node:15.1
    # Then run your tests!
    # CircleCI will report the results back to your VCS provider.
    steps:
      # Checkout the code as the first step.
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test
  deploy:
  executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            ##- run: sudo apt-get install rsync && rsync --version
            ##- run: rsync -a -e "ssh -o StrictHostKeyChecking=no" dist/ centos@X.XX.XXX.XXX:~/reactfrontend/
            ##- run:
            ##    name: Deploy Final
            ##   command: |
            ##      ssh centos@X.XX.XXX.XXX "sudo rsync -a /home/centos/reactfrontend/ /usr/share/nginx/html/"

workflows:
  # Below is the definition of your workflow.
  build-yest-and-deploy:
    jobs:
      - build-and-test:
      - deploy:
            filters:
              branches:
                only: main # only deploy on the main branch
