
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:
    
    docker:
      - image: cimg/node:15.1
    # Then run your tests!
    # CircleCI will report the results back to your VCS provider.
    steps:
      # Checkout the code as the first step.
      - checkout
      - node/install-packages
      - run: npm run build
      - run: npm test
      - run:
          name: Deploy final
          command: deplment cmd
            ##- run: sudo apt-get install rsync && rsync --version
            ##or
            ## - run ssh -oStictHostKeyChecking=no - $USER@$IP "./deploy.sh"
            

workflows:
  # Below is the definition of your workflow.
  build-and-test:
    jobs:
      - build-and-test:
            filters:
              branches:
                only: main # only deploy on the main branch
